name: Deploy to GCP

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2  

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2 
      with:
        project_id: 'cs1660-static-site-420621' 
        workload_identity_provider: 'projects/898637905791/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'git-service-account@cs1660-static-site-420621.iam.gserviceaccount.com'

    - id: 'upload-static-files' 
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'public'
        destination: 'hannah-static-site-bucket'
        parent: false
